# Generated by Django 3.2.5 on 2021-11-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravintolat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravintola',
            name='name',
            field=models.TextField(),
        ),
    ]
